In [9]:
from sklearn.preprocessing import Binarizer

# 原始數據
data = [[-1, 2, 0],
        [3, -2, 1],
        [0, 1, 0]]

# 使用預設閾值 0 進行二值化
binarizer = Binarizer()
binarized_data = binarizer.fit_transform(data)

print(binarized_data)

[[0 1 0]
 [1 0 1]
 [0 1 0]]


In [12]:
# 使用閾值 1 進行二值化
binarizer = Binarizer(threshold=1)
binarized_data = binarizer.fit_transform(data)

print(binarized_data)

[[0 1 0]
 [1 0 0]
 [0 0 0]]


In [8]:
import numpy as np

# 假設我們只想對第一列進行二值化
data = np.array([[1.5, -2.3, 3.1], [4.5, 5.0, -0.5], [2.2, 3.3, 0.7]])

# 對第一列數據進行二值化，閾值設置為 2
binarizer = Binarizer(threshold=2)
binarized_data = binarizer.fit_transform(data[:, 0].reshape(-1, 1))

print(binarized_data)

[[0.]
 [1.]
 [1.]]
