## 邏輯回歸模型

In [1]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import numpy as np

# 創建一個簡單的數據集
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
y = np.array([0, 1, 0, 1])

# 使用邏輯回歸作為基礎模型
model = LogisticRegression()

# 使用 RFE 進行特徵選擇，選擇 2 個最具影響力的特徵
rfe = RFE(estimator=model, n_features_to_select=2)
fit = rfe.fit(X, y)

print("原始數據：\n", X)
print("是否選中特徵：", fit.support_)
print("每個特徵的排名：", fit.ranking_) # 排名越小，特徵越重要
print("經過特徵選擇後的數據：\n", fit.transform(X))


原始數據：
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
是否選中特徵： [False  True  True]
每個特徵的排名： [2 1 1]
經過特徵選擇後的數據：
 [[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]


## 隨機森林


In [2]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE

# 創建一個數據集
X = np.array([[10, 15, 1], [25, 30, 0], [20, 35, 1], [30, 40, 0]])
y = np.array([0, 1, 0, 1])

# 使用隨機森林分類器作為基礎模型
clf = RandomForestClassifier(n_estimators=100)

# 使用 RFE 進行特徵選擇，選擇 2 個特徵
rfe = RFE(estimator=clf, n_features_to_select=2)
fit = rfe.fit(X, y)

print("原始數據：\n", X)
print("是否選中特徵：", fit.support_)
print("每個特徵的排名：", fit.ranking_)
print("經過特徵選擇後的數據：\n", fit.transform(X))


原始數據：
 [[10 15  1]
 [25 30  0]
 [20 35  1]
 [30 40  0]]
是否選中特徵： [ True False  True]
每個特徵的排名： [1 2 1]
經過特徵選擇後的數據：
 [[10  1]
 [25  0]
 [20  1]
 [30  0]]
