## Random forest

In [1]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
import numpy as np

# 創建一個簡單的數據集
X = np.array([[1, 0, 3], [4, 0, 6], [7, 0, 9], [10, 0, 12]])
y = np.array([0, 1, 0, 1])

# 使用隨機森林分類器作為基礎模型
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X, y)

# 使用 SelectFromModel 進行特徵選擇
selector = SelectFromModel(clf, threshold="mean", prefit=True)
X_new = selector.transform(X)

print("原始數據：\n", X)
print("經過特徵選擇後：\n", X_new)
print("選擇的重要特徵索引：", selector.get_support(indices=True))


原始數據：
 [[ 1  0  3]
 [ 4  0  6]
 [ 7  0  9]
 [10  0 12]]
經過特徵選擇後：
 [[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]
選擇的重要特徵索引： [0 2]


## L1 Norm

In [2]:
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel

# 創建一個簡單的數據集
X = np.array([[0.1, 1.1, 0.5], [0.2, 1.2, 0.6], [0.3, 1.3, 0.7], [0.4, 1.4, 0.8]])
y = np.array([1, 2, 3, 4])

# 使用 Lasso 作為基礎模型
lasso = Lasso(alpha=0.1)
lasso.fit(X, y)

# 使用 SelectFromModel 進行特徵選擇
selector = SelectFromModel(lasso, threshold="mean", prefit=True)
X_new = selector.transform(X)

print("原始數據：\n", X)
print("經過特徵選擇後：\n", X_new)
print("選擇的重要特徵索引：", selector.get_support(indices=True))


原始數據：
 [[0.1 1.1 0.5]
 [0.2 1.2 0.6]
 [0.3 1.3 0.7]
 [0.4 1.4 0.8]]
經過特徵選擇後：
 [[0.1]
 [0.2]
 [0.3]
 [0.4]]
選擇的重要特徵索引： [0]
