In [1]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# 原始數據
data = np.array([[1.0, 2.0], [3.0, 6.0], [5.0, 8.0], [7.0, 10.0]])

# 創建 StandardScaler 並對數據進行標準化
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[-1.34164079 -1.52127766]
 [-0.4472136  -0.16903085]
 [ 0.4472136   0.50709255]
 [ 1.34164079  1.18321596]]


In [2]:
# 保存均值與標準差
print("均值:", scaler.mean_)
print("標準差:", scaler.scale_)


均值: [4.  6.5]
標準差: [2.23606798 2.95803989]


In [3]:
# 反轉標準化
original_data = scaler.inverse_transform(scaled_data)
print(original_data)


[[ 1.  2.]
 [ 3.  6.]
 [ 5.  8.]
 [ 7. 10.]]


In [4]:
# 多個特徵數據集
data = np.array([[1.0, 100.0], [2.0, 150.0], [3.0, 200.0], [4.0, 300.0]])

# 對多個特徵進行標準化
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[-1.34164079 -1.18321596]
 [-0.4472136  -0.50709255]
 [ 0.4472136   0.16903085]
 [ 1.34164079  1.52127766]]


In [5]:
# 不進行數據的中心化，只進行標準差縮放
scaler = StandardScaler(with_mean=False)
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[0.89442719 1.35224681]
 [1.78885438 2.02837021]
 [2.68328157 2.70449362]
 [3.57770876 4.05674042]]


In [6]:
# 測試數據
test_data = np.array([[2.0, 120.0]])

# 使用與訓練數據相同的標準化參數對測試數據進行轉換
scaled_test_data = scaler.transform(test_data)

print(scaled_test_data)


[[1.78885438 1.62269617]]
