In [6]:
from sklearn.feature_selection import VarianceThreshold
import numpy as np

# 創建一個數據集，其中一些特徵的值完全相同
data = np.array([
    [0.0, 1, 0.0, 3],
    [0.0, 2, 0.0, 4],
    [0.0, 3, 0.0, 3],
    [0.0, 4, 0.0, 1]
])

# 計算每個特徵的方差
variances = np.var(data, axis=0) # axis = 0 -> 以column方向計算
print("每個特徵的方差值：", variances)

# 使用 VarianceThreshold 移除方差為 0 的特徵
selector = VarianceThreshold()
reduced_data = selector.fit_transform(data)

print("原始數據：\n", data)
print("移除方差為 0 的特徵後：\n", reduced_data)


每個特徵的方差值： [0.     1.25   0.     1.1875]
原始數據：
 [[0. 1. 0. 3.]
 [0. 2. 0. 4.]
 [0. 3. 0. 3.]
 [0. 4. 0. 1.]]
移除方差為 0 的特徵後：
 [[1. 3.]
 [2. 4.]
 [3. 3.]
 [4. 1.]]


In [10]:
# 創建一個包含不同方差的數據集
data = np.array([
    [0, 2, 0.2],
    [0, 1, 0.1],
    [0, 2, 0.2],
    [0, 1, 0.3]
])

# 計算每個特徵的方差
variances = np.var(data, axis=0)
print("每個特徵的方差值1：", variances)

# 設定閾值，移除方差小於 0.2 的特徵
selector = VarianceThreshold(threshold=0.2)
reduced_data = selector.fit_transform(data)

# 查看方差值
print("每個特徵的方差值2：", selector.variances_)

print("原始數據：\n", data)
print("移除方差小於 0.2 的特徵後：\n", reduced_data)


每個特徵的方差值1： [0.    0.25  0.005]
每個特徵的方差值2： [0.    0.25  0.005]
原始數據：
 [[0.  2.  0.2]
 [0.  1.  0.1]
 [0.  2.  0.2]
 [0.  1.  0.3]]
移除方差小於 0.2 的特徵後：
 [[2.]
 [1.]
 [2.]
 [1.]]
